-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_study_participant_sequence`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_study_participant_sequence
-- *
-- * NIHR Bioresource study participant sequence table
-- *
-- *******************************************************/
CREATE TABLE `civicrm_study_participant_sequence` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique StudyParticipantSequence ID',
     `study_number` varchar(32)    COMMENT 'Study Number',
     `sequence` int unsigned    COMMENT 'Sequence number for study participant id' 
,
        PRIMARY KEY (`id`)
 
    ,     UNIQUE INDEX `index_study_number`(
        study_number
  )
  
 
)    ;

 